version: 0.2
env:
  secrets-manager:
    GITHUB_PASSWORD: xilution-github-credentials:password
    GITHUB_TOKEN: xilution-github-credentials:token
    GITHUB_USER: xilution-github-credentials:username
    NPM_PASSWORD: xilution-npm-credentials:password
    NPM_TOKEN: xilution-npm-credentials:token
    NPM_USERNAME: xilution-npm-credentials:username
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - git clone https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/xilution/$REPOSITORY.git
      - cd $REPOSITORY
      - npm ci

  pre_build:
    commands:
      - npm test

  build:
    commands:
      - npm run build
      - npx semantic-release
